### ISSUE TITLE
--ignore and tables without primary key

### ISSUE THREAD

**Issue by bitchkat** [willbryant/kitchen_sync#24]
I'm brand new to ks and am using it sync a drupal database between production and my development environment. Its failing on the following error:

Error in the 'from' worker: Couldn't find a primary or non-nullable unique key on table uc_payment_paypal_ipn

which comes from the contributed drupal7 module, ubercart.  I can most likely add a primary key but why doesn't --ignore uc_payment_paypal_ipn work around this problem?

**Comment by willbryant** [comment]
Hmm yeah, it should eh.  I guess the problem is that it does the schema structure determination stuff before it applies the 'ignore' stuff, and the schema stuff blows up itself.  Should be possible to apply the ignore set earlier.  Or to do the blowing up later.  Either would work.

Don't suppose you could send me a test case?

**Comment by bitchkat** [comment]
Did you get dump I sent via email?

**Comment by willbryant** [comment]
Yep.  Any chance you could turn it into a test?  They're in Ruby if C++ isn't your thing.  Should only need the schema - it hasn't started looking at the data at the point that error occurs.
