### ISSUE TITLE
ks >= 1.2 cannot sync from server with version 1.0 using `--via`

### ISSUE THREAD

**Issue by aclemons** [willbryant/kitchen_sync#49]
I've packaged both v1.6 and v1.7 and run into the following problem. I have a server with kitchen sync 1.0 installed and am trying to sync (mysql) from it using either of these version with the `--via` option. This fails with the error:

```
Kitchen Sync
This program is a part of Kitchen Sync.  Instead of running this program directly, run 'ks'.
Couldn't start Kitchen Sync over SSH to myserver.  Please check that you can SSH to that server yourself, and that Kitchen Sync's binary can be found on that system at ks_mysql.
```

I have bisected this and fdbdd2c is the commit which broke compatibility. Do you expect a newer client to be able to speak to the server running 1.0? d3f7c09 it not part of 1.0 so, the server cannot answer the do-nothing request. Since fdbdd2c made this now fatal, compatibility is broken. In my case, the server is unfortunately not under my control, so getting a newer ks installed will take some time.

**Comment by willbryant** [comment]
We did know that that change would unfortunately break backwards compatibility, which is why I got Dylan to split the change into two (PRs #38 and #40) and we released them in successive releases (1.1 and 1.2).

I don't really have a formal backwards-compatibility rule on versioning at the moment, but it's basically rolling (to give people a chance to upgrade their client/server fleet): ignoring the pre-stable versions (<1.0), each release can talk to at least the previous release.

We could adopt semver, in which case I would have had to bump to 2.0, but I guess it doesn't really change the underlying issue.

Not sure if it helps but KS doesn't have to be installed system-wide to work - you can compile and run it from your home directory (or even two directories that don't match, using the `--from-path` option).  Are you able to compile on (or copy binaries onto) the source system?

**Comment by aclemons** [comment]
Sorry, I just saw you edited the title. I thought I had a typo. I've reverted it back now.

**Comment by aclemons** [comment]
Yes I can copy binaries to the system, but there are a couple of different servers for different environments, so it was easier to just wrap the whole thing in a shell wrapper which opens the tunnel and runs ks and kills the tunnel again.

I maintain the [kitchen-sync package](https://repology.org/metapackage/kitchen-sync/versions) for Slackware and currently have the version at 1.5. I don't want to break anyone's workflow by moving to a version > 1.5.

I could patch out the fatal error and just leave the warning on stderr which would mirror the behaviour up to version 1.5. Did you consider having a command line switch to skip the server greeting?

**Comment by willbryant** [comment]
Hmm, something's wrong here.

My understanding was that it was already fatal before fdbdd2c.  I thought it was meant to be.

You have found it definitely works with 1.5?

**Comment by aclemons** [comment]
Yes, I am using kitchen-sync 1.5 built from [here](https://slackbuilds.org/repository/14.2/system/kitchen-sync/) and talking to a 1.0. server.

**Comment by willbryant** [comment]
Oh, ok.

**Comment by aclemons** [comment]
It just complains on stderr that the server does not understand the do nothing request

```
Kitchen Sync
This program is a part of Kitchen Sync.  Instead of running this program directly, run 'ks'.
failed to perform initial SSH greeting
Finished Kitchen Syncing.
```

**Comment by willbryant** [comment]
Ah right, I see.

Up to you I guess?  The time window between 1.0 and 1.1 was relatively narrow and the userbase was pretty small at that time so I don't think it's going to affect too many people, but you've got a real case.  Patching it back to 1.5 behavior doesn't seem unreasonable, but how long will you keep backwards compatibility for?

I guess with a bit more effort it could have been made to use the existing `from` command and talk the real protocol to get through startup & quit cleanly instead of introducing the new `do-nothing` command.  (It's not zero effort because at the moment the "parent" process, the `ks` command itself, doesn't do any channel IO, it just spawns the other binaries and checks exit results.)  That would have been backwards-compatible with 1.0 too, I think.

**Comment by willbryant** [comment]
Oh, you have stable releases, I see.  Yeah, sounds reasonable.  I'll close for now but feel free to reopen if that doesn't work out.

**Comment by willbryant** [comment]
Changed title back since you were right in the first place :)
