### ISSUE TITLE
Support syncing enum types

### ISSUE THREAD

**Issue by Hyukishi** [willbryant/kitchen_sync#70]
I don't see the answer anywhere in the filtering documentation so it may not be possible at this time, but I would like to exclude an entire column for a table that is being synchronized because the column is enumerated with the default of NULL and the only values able to be set as "Yes" or "No" and kitchen-sync fails with the message:
`Kitchen Sync
Don't know how to interpret type of app.abandoned_equipment (enum('Yes','No')).  Please check https://github.com/willbryant/kitchen_sync/blob/master/SCHEMA.md.
Kitchen Syncing failed.`

**Comment by willbryant** [comment]
Hmm yeah, unfortunately there's no way to ignore a column in that sense at the moment.  It expects to encode every column, including those replaced by some other expression in the filter file.

But the good news is that I'm working on improving the type system for the next release.  So far spatial is done and JSON is nearly done (just trying to improve support for older versions without that type at the moment).  In the future I hope to support syncing arbitrary (non-portable) data types.

But since enums should be portable, I can try implementing support using the current approach.  I'll work on that next :).  I will change the title of this issue to cover that.

**Comment by willbryant** [comment]
@Hyukishi do you ever have more than one column with the same enumeration values?

I'm trying to decide the best way to represent enumerations.

**Comment by Hyukishi** [comment]
Yes, in fact the table containing the previous enumerated column does have
a few more in it.

**Comment by willbryant** [comment]
Are you using mysql or postgresql?

**Comment by Hyukishi** [comment]
MySQL 5.7

**Comment by willbryant** [comment]
Try again on master :)
